CREATE TABLE [dbo].[Books]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [DBName] NVARCHAR(50) NOT NULL, 
    [Title] NVARCHAR(50) NULL, 
    [Rating] FLOAT NULL DEFAULT 0,
    [UpdateDate] DATETIME NULL DEFAULT GETDATE(), 
    [DeleteDate] DATETIME NULL, 
    CONSTRAINT UC_Books UNIQUE (DBName)
)
